### PR TITLE
Disable Rust dependencies while building cryptography for Docker

### PR DESCRIPTION
**Pull request by gabriel-milan**
## Summary

Fixes ARM builds for Docker (using one of two available approaches, see details below) (related to https://github.com/Drakkar-Software/OctoBot/issues/1579 and https://github.com/Drakkar-Software/OctoBot/pull/1606).

Solve the issue: #1579

## Changelog

  - Removes Rust dependencies for Python's cryptography package while building Docker image.

## What's new?

Due to cryptography's recent dependencies on Rust (https://github.com/pyca/cryptography/issues/5771), Raspberry Pi's arm/v7 platform (among others) became unsupported. In order to fix that, there are currently two available approaches:

* Disable Rust while building cryptography with the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1` (chosen in this case)
  * Keeps cryptography up to date
  * I couldn't really find the downsides of disabling Rust
* Use an older version of cryptography (`2.6.1` works fine for me in other projects)
  * Cryptography is outdated, can lead to security issues

You can see that when I've tried to build it using the Dockerfile I've customized it seems that [the build has gone OK](https://github.com/gabriel-milan/OctoBot/pull/3/checks?check_run_id=2175721455) but, unfortunately, there's this issue:

```
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = docker exporter does not currently support exporting manifest lists
``` 

Fortunately, this isn't related to the Docker image itself, but this: https://github.com/docker/buildx/issues/59.

The purpose of this PR is to find out if this change to the Dockerfile is acceptable. If so, I can implement what is missing.

### CODE REVIEW

**Review by Herklos — APPROVED** [review]
Thanks @gabriel-milan good job ! 👍

**Comment by GuillaumeDSM** [comment]
I included your commit here https://github.com/Drakkar-Software/OctoBot/pull/1612 to apply it on an updated branch, thanks a lot @gabriel-milan !

**Comment by gabriel-milan** [comment]
Thank you guys, can't wait to get this up and running on my RPi.

**Comment by GuillaumeDSM** [comment]
merged via https://github.com/Drakkar-Software/OctoBot/pull/1612
we will soon have OctoBot back on armv7 🎉

**Pull request closed without merging**
