### PR TITLE
[Tests] Coinbase advanced

### PR DESCRIPTION
**Pull request by GuillaumeDSM**
requires trading version with https://github.com/Drakkar-Software/OctoBot-Trading/pull/880
requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/916

### CODE REVIEW

**Review by Herklos — APPROVED** [review]

**Comment by DrBlackross** [comment]
does it work lol, tried with latest pull via docker, CoinbasePro is still in there but no CBadvance-trade setting.

**Comment by Herklos** [comment]
> does it work lol, tried with latest pull via docker, CoinbasePro is still in there but no CBadvance-trade setting.
> 
> pro works but doesnt except incoming "deposits from the same address" which is odd...

Hi @DrBlackross, did you try with latest tentacles? You need to set an environment variable to download latest tentacles with latest docker image

**Comment by DrBlackross** [comment]
is there a post here somewhere as a reference?

**Comment by Herklos** [comment]
You can find some documentation here: https://developer.octobot.info/coding/environment-variables#global-variables

**Comment by GuillaumeDSM** [comment]
Please use the "Coinbase" exchange instead. It is using Coinbase advanced. Coinbase Pro should not be used anymore

**Comment by DrBlackross** [comment]
when generating a new key (api/secret) there is no password in the coinbase account setting, so i left it defaulted first then blanked it. keep getting this error...

 2023-04-10 10:14:40,081 ERROR    ExchangeHistoryDataCollector Error when collecting coinbase history for DOGE/USDT:  (AuthenticationError)

**Comment by GuillaumeDSM** [comment]
Coinbase is the only exchange that requires authentication all the time. It's refusing to give data to unauthenticated used unfortunatelly. You can have it working by adding your API keys and still being on simulator

**Comment by DrBlackross** [comment]
-also-
in both real and simulated trading cant pull historical data... BUT, it does pull my balance on coinbase

**Comment by DrBlackross** [comment]
> -also- in both real and simulated trading cant pull historical data... BUT, it does pull my balance on coinbase

i'll let it run for about 4 hours and see if it'll pull/build its own data... but here's the errors i get when trying to pull historical data from the "coinbase" DOGE/USDT market with the precompiled binary 4.4.7 (dropped docker side of things for now)...

2023-04-10 10:37:30,897 ERROR    ExchangeHistoryDataCollector 
Traceback (most recent call last):
  File "octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py", line 88, in octobot_trading.exchanges.connectors.ccxt.ccxt_connector.CCXTConnector.initialize_impl
  File "octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py", line 89, in octobot_trading.exchanges.connectors.ccxt.ccxt_connector.CCXTConnector.initialize_impl
  File "octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py", line 109, in load_symbol_markets
  File "ccxt/async_support/base/exchange.py", line 194, in load_markets
  File "ccxt/async_support/base/exchange.py", line 190, in load_markets
  File "ccxt/async_support/base/exchange.py", line 180, in load_markets_helper
  File "ccxt/async_support/coinbase.py", line 859, in fetch_markets
  File "ccxt/async_support/coinbase.py", line 931, in fetch_markets_v3
  File "ccxt/async_support/base/exchange.py", line 1319, in request
  File "ccxt/async_support/base/exchange.py", line 1315, in fetch2
  File "ccxt/async_support/coinbase.py", line 2587, in sign
  File "ccxt/async_support/base/exchange.py", line 1472, in check_required_credentials
ccxt.base.errors.AuthenticationError: coinbase requires "apiKey" credential

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/1tb/octobot/tentacles/Backtesting/collectors/exchanges/exchange_history_collector/history_collector.py", line 56, in start
    self.exchange_manager = await trading_api.create_exchange_builder(self.config, self.exchange_name) \
  File "octobot_trading/exchanges/exchange_builder.py", line 47, in build
  File "octobot_trading/exchanges/exchange_builder.py", line 43, in octobot_trading.exchanges.exchange_builder.ExchangeBuilder.build
  File "octobot_trading/exchanges/exchange_builder.py", line 81, in _build_exchange_manager
  File "octobot_trading/exchanges/exchange_builder.py", line 63, in octobot_trading.exchanges.exchange_builder.ExchangeBuilder._build_exchange_manager
  File "octobot_trading/util/initializable.py", line 28, in initialize
  File "octobot_trading/exchanges/exchange_manager.py", line 88, in initialize_impl
  File "octobot_trading/exchanges/exchange_factory.py", line 35, in create_exchanges
  File "octobot_trading/exchanges/exchange_factory.py", line 57, in create_real_exchange
  File "octobot_trading/exchanges/abstract_exchange.py", line 83, in initialize
  File "octobot_trading/exchanges/types/rest_exchange.py", line 95, in initialize_impl
  File "octobot_trading/exchanges/abstract_exchange.py", line 83, in initialize
  File "octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py", line 98, in initialize_impl
ccxt.base.errors.AuthenticationError
 2023-04-10 10:37:30,900 ERROR    ExchangeHistoryDataCollector Error when collecting coinbase history for DOGE/USDT:  (AuthenticationError)

i can get the coinbase side to display my portfolio (cool.. used the ./Octobot* --encrypter to add just those two lines into my ./user/config.json file and removed the 3rd option (password) in the coinbase part).

Till then lets give it 4 to 5 hours lol

*sidenote... when playing with the docker image and chatGPT i noticed it didnt use chatGPT key/account at all for me, in the future would there be an option for alpaca-lora?

**Comment by GuillaumeDSM** [comment]
We will have a look on the coinbase issues. Thanks @DrBlackross.
About alpaca-lora, you can set the `GPT_MODEL` env variable to "alpaca-lora" and it will use it

**Pull request merged**
