### PR TITLE
#655 added dev-mode check in evaluators display

### PR DESCRIPTION
**Pull request by GuillaumeDSM**
image

no info => activated

class param
    DEV_MODE = True
=> not displayed

### CODE REVIEW

**Comment by Herklos** [comment]
I don't think this is the best way to check if the current tentacle is in dev mode.

This information is provided in the json description.

**Comment by GuillaumeDSM** [comment]
> I don't think this is the best way to check if the current tentacle is in dev mode.
> 
> This information is provided in the json description.

On the scale of a tentacle yes but not on multi evaluators tentacles

**Comment by Herklos** [comment]
> 
> 
> > I don't think this is the best way to check if the current tentacle is in dev mode.
> > This information is provided in the json description.
> 
> On the scale of a tentacle yes but not on multi evaluators tentacles

A multi-evaluator tentacle ?

**Comment by GuillaumeDSM** [comment]
> > I don't think this is the best way to check if the current tentacle is in dev mode.
> > This information is provided in the json description.
> 
> On the scale of a tentacle yes but not on multi evaluators tentacles

Actually, dev_mode is not the right label, it should be 

> > > I don't think this is the best way to check if the current tentacle is in dev mode.
> > > This information is provided in the json description.
> > 
> > 
> > On the scale of a tentacle yes but not on multi evaluators tentacles
> 
> A multi-evaluator tentacle ?

I mean in default tentacles we have files with more than one evaluator => we need a way not to display them all if some are not to be used yet

**Comment by Herklos** [comment]
> 
> 
> > > I don't think this is the best way to check if the current tentacle is in dev mode.
> > > This information is provided in the json description.
> > 
> > 
> > On the scale of a tentacle yes but not on multi evaluators tentacles
> 
> Actually, dev_mode is not the right label, it should be
> 
> > > > I don't think this is the best way to check if the current tentacle is in dev mode.
> > > > This information is provided in the json description.
> > > 
> > > 
> > > On the scale of a tentacle yes but not on multi evaluators tentacles
> > 
> > 
> > A multi-evaluator tentacle ?
> 
> I mean in default tentacles we have files with more than one evaluator => we need a way not to display them all if some are not to be used yet

Hum ok I see, but I think this is not the best solution to duplicate this option (DEV_MODE) because we have multiple evaluator in some files. I think we have to choose between : 
- The description for the whole file (same for each evaluator in file)
- To move evaluator in development in a different file with a new description (and eventually move it back to the original file)
- Don't enable multi-evaluator files.

**Comment by GuillaumeDSM** [comment]
> > > > I don't think this is the best way to check if the current tentacle is in dev mode.
> > > > This information is provided in the json description.
> > > 
> > > 
> > > On the scale of a tentacle yes but not on multi evaluators tentacles
> > 
> > 
> > Actually, dev_mode is not the right label, it should be
> > > > > I don't think this is the best way to check if the current tentacle is in dev mode.
> > > > > This information is provided in the json description.
> > > > 
> > > > 
> > > > On the scale of a tentacle yes but not on multi evaluators tentacles
> > > 
> > > 
> > > A multi-evaluator tentacle ?
> > 
> > 
> > I mean in default tentacles we have files with more than one evaluator => we need a way not to display them all if some are not to be used yet
> 
> Hum ok I see, but I think this is not the best solution to duplicate this option (DEV_MODE) because we have multiple evaluator in some files. I think we have to choose between :
> 
> * The description for the whole file (same for each evaluator in file)
> * To move evaluator in development in a different file with a new description (and eventually move it back to the original file)
> * Don't enable multi-evaluator files.

I think moving them to a different file is the best solution.
A description for the whole file is very unflexible, same with not allowing multi evaluator files.

**Comment by GuillaumeDSM** [comment]
See https://github.com/Drakkar-Software/OctoBot-Tentacles/commits/dev

**Comment by Herklos** [comment]
Perfect ! 👍

**Pull request closed without merging**
