### PR TITLE
[Doc]  Update README links

### PR DESCRIPTION
**Pull request by Herklos**

### CODE REVIEW

**Comment by GuillaumeDSM** [comment]
should we add something to identify that it comes from github or its handled by click ?

**Comment by Herklos** [comment]
> should we add something to identify that it comes from github or its handled by click ?

I don't know

**Comment by GuillaumeDSM** [comment]
> > should we add something to identify that it comes from github or its handled by click ?
> 
> I don't know

we merge and check ?

**Comment by GuillaumeDSM** [comment]
-

> > > should we add something to identify that it comes from github or its handled by click ?
> > 
> > 
> > I don't know
> 
> we merge and check ?

we actually should be able to check already from this PR

**Comment by Herklos** [comment]
> should we add something to identify that it comes from github or its handled by click ?

Done. There was no referral information. I added a `gh-` prefix to links

**Review by GuillaumeDSM — APPROVED** [review]
👍

**Pull request merged**
