### PR TITLE
[CI] Add codeql workflow

### PR DESCRIPTION
**Pull request by Herklos**
Recommended by github in https://github.com/Drakkar-Software/OctoBot/security/code-scanning

### CODE REVIEW

**Review by GuillaumeDSM — COMMENTED** [review]
image
should we handle these warnings ?

**Comment by Herklos** [comment]
> image
> should we handle these warnings ?

I don't know, you think we should install dependencies ?

**Comment by Herklos** [comment]
> image
> should we handle these warnings ?

You right, there is an issue with dependencies installation. It's probably due to python version

**Comment by GuillaumeDSM** [comment]
> > image
> > should we handle these warnings ?
> 
> You right, there is an issue with dependencies installation. It's probably due to python version

It looks like there is something with python2

**Comment by Herklos** [comment]
Worked in https://github.com/Drakkar-Software/OctoBot/runs/1636945938. I'll now change event trigger to `branches: [ master, dev ]` only as recommended.

**Review by GuillaumeDSM — APPROVED** [review]
great !

**Pull request merged**
