### PR TITLE
TEMP test arm build

### PR DESCRIPTION
**Pull request by GuillaumeDSM**
Thank you for sending your pull request. 
But first, have you included unit tests, and is your code PEP8 conformant? [More details](https://github.com/Drakkar-Software/OctoBot/blob/dev/CONTRIBUTING.md)

## Summary
Explain in one sentence the goal of this PR

Solve the issue: #___

## Changelog

  - _____
  - _____
  - _____

## What's new?
*Explain in details what this PR solve or improve.*

### CODE REVIEW

**Comment by Tedezed** [comment]
I don't know if it will help you, I guess you will know thisl: `docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 -t drakkarsoftware/octobot:0.4.0b8 .`

**Comment by Tedezed** [comment]
In case it helps you  `docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64`

**Comment by Herklos** [comment]
> In case it helps you `docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64`

Hi @Tedezed, thanks for your help but we already use buildx builder :wink: 
The issue we are trying to investigate here is the build time of armv7. It lasts more than 6h and github doesn't allow a build longer than 6h

**Comment by Tedezed** [comment]
I saw that they already have cache implemented, I will try to see the process in case something occurs to me

**Comment by Herklos** [comment]
@GuillaumeDSM with the recent changes, I think we should retry this experimentation

**Pull request closed without merging**
