### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by Herklos**

### CODE REVIEW

**Comment by GuillaumeDSM** [comment]
add Telegram and Discord channels as well as Twitter page :)

**Comment by Herklos** [comment]
Telegram invitation link : https://t.me/joinchat/F9cyfxV97ZOaXQ47H5dRWw
Discord invitation link : https://discord.gg/vHkcb8W

**Comment by GuillaumeDSM** [comment]
Telegram channel : https://t.me/joinchat/F9cyfxV97ZOaXQ47H5dRWw
Discord channel link : https://discord.gg/vHkcb8W

better no ?

**Comment by Herklos** [comment]
I am searching for a github badge in shields.io

**Comment by Herklos** [comment]
And discord (waiting for server to enable widget) : 
[Discord](https://discord.gg/vHkcb8W)

**Pull request merged**
