### PR TITLE
[Docs] Describe how to open admin CMD

### PR DESCRIPTION
**Pull request by valouvaliavlo**

### CODE REVIEW

**Review by GuillaumeDSM — APPROVED** [review]
👍

**Review by Herklos — APPROVED** [review]

**Comment by Herklos** [comment]
@valouvaliavlo can you rebase your branch on origin/dev please ?

**Comment by valouvaliavlo** [comment]
> @valouvaliavlo can you rebase your branch on origin/dev please ?
it's done

**Comment by Herklos** [comment]
> > @valouvaliavlo can you rebase your branch on origin/dev please ?
> 
> it's done

Can you rebase on DrakkarSoftware/dev please ?

**Comment by valouvaliavlo** [comment]
> > > @valouvaliavlo can you rebase your branch on origin/dev please ?
> > 
> > 
> > it's done
> 
> Can you rebase on DrakkarSoftware/dev please ?

it's ok

**Comment by Herklos** [comment]
Thanks !

**Pull request merged**
