### PR TITLE
Implement travis & appveyor CI release

### PR DESCRIPTION
**Pull request by Herklos**
Implement travis release

### CODE REVIEW

**Comment by Herklos** [comment]
Add temporary fix for windows binary due to current bug in pyinstaller (https://github.com/nltk/nltk/issues/2159)

(PR that fix : https://github.com/pyinstaller/pyinstaller/pull/3897 https://github.com/pyinstaller/pyinstaller/pull/3932)

**Comment by Herklos** [comment]
To build bootloader : https://pythonhosted.org/PyInstaller/bootloader-building.html

**Comment by Herklos** [comment]
WIP : appveyor prevent build when no tag

**Comment by GuillaumeDSM** [comment]
Good job !

**Pull request merged**
