### PR TITLE
Disable rust compile on dockerfile

### PR DESCRIPTION
**Pull request by GuillaumeDSM**
Based on https://github.com/Drakkar-Software/OctoBot/pull/1611
thanks to @gabriel-milan

### CODE REVIEW

**Review by Herklos — APPROVED** [review]
Nice ! :tada:

**Comment by Herklos** [comment]
Still running after ~3h :smile:

**Comment by gabriel-milan** [comment]
Yeah [same thing that happened to mine](https://github.com/Drakkar-Software/OctoBot/pull/1612/checks?check_run_id=2178369363#step:12:4152). 

```
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = docker exporter does not currently support exporting manifest lists
```

Idk why this is happening as this is the official Docker GH action.

**Comment by gabriel-milan** [comment]
Update: I was able to build it on my RPi as it is on the [disable_rust_compile_on_dockerfile](https://github.com/Drakkar-Software/OctoBot/tree/disable_rust_compile_on_dockerfile) branch. It took a while though (~2.5 hours). I'll try to come up with something for this GH action that's failing.

**Comment by GuillaumeDSM** [comment]
> Update: I was able to build it on my RPi as it is on the [disable_rust_compile_on_dockerfile](https://github.com/Drakkar-Software/OctoBot/tree/disable_rust_compile_on_dockerfile) branch. It took a while though (~2.5 hours). I'll try to come up with something for this GH action that's failing.

Great news !
Thanks for this @gabriel-milan

**Comment by gabriel-milan** [comment]
Well, it seems to be OK (https://github.com/gabriel-milan/OctoBot/pull/3/checks?check_run_id=2183699151).

Apparently, when you use `--load` (or `load: true` on the YAML), you're forcing the builder driver to `docker` (see [docs](https://docs.docker.com/engine/reference/commandline/buildx_build/)) and for now it still doesn't support multi-platform builds (as previously mentioned on https://github.com/docker/buildx/issues/59). By removing it, it builds just fine.

I'm not quite sure that, by doing this, the caching mechanism will work, but I think it will. Besides that, [this GH action](https://github.com/dawidd6/action-docker-publish-changed) looks like an alternative if we can't dig deeper on this issue.

Finally, I think that the only thing that still needs changing on the Dockerfile is on lines [150](https://github.com/gabriel-milan/OctoBot/blob/fix/docker-arm/.github/workflows/docker.yml#L150) and [169](https://github.com/gabriel-milan/OctoBot/blob/fix/docker-arm/.github/workflows/docker.yml#L169) (in my current version) by adding `linux/arm/v7` to the platform list.

**Review by Herklos — APPROVED** [review]

**Comment by gabriel-milan** [comment]
It's me again, guys. I've checked and I think that this

> Finally, I think that the only thing that still needs changing on the Dockerfile is on lines [150](https://github.com/gabriel-milan/OctoBot/blob/fix/docker-arm/.github/workflows/docker.yml#L150) and [169](https://github.com/gabriel-milan/OctoBot/blob/fix/docker-arm/.github/workflows/docker.yml#L169) (in my current version) by adding `linux/arm/v7` to the platform list.

is still missing. Would you like me to commit it somewhere or you guys can do it?

**Comment by GuillaumeDSM** [comment]
> It's me again, guys. I've checked and I think that this
> 
> > Finally, I think that the only thing that still needs changing on the Dockerfile is on lines [150](https://github.com/gabriel-milan/OctoBot/blob/fix/docker-arm/.github/workflows/docker.yml#L150) and [169](https://github.com/gabriel-milan/OctoBot/blob/fix/docker-arm/.github/workflows/docker.yml#L169) (in my current version) by adding `linux/arm/v7` to the platform list.
> 
> is still missing. Would you like me to commit it somewhere or you guys can do it?

I created this PR, is it what you where thinking to add ? https://github.com/Drakkar-Software/OctoBot/pull/1616

**Comment by gabriel-milan** [comment]
> > It's me again, guys. I've checked and I think that this
> > > Finally, I think that the only thing that still needs changing on the Dockerfile is on lines [150](https://github.com/gabriel-milan/OctoBot/blob/fix/docker-arm/.github/workflows/docker.yml#L150) and [169](https://github.com/gabriel-milan/OctoBot/blob/fix/docker-arm/.github/workflows/docker.yml#L169) (in my current version) by adding `linux/arm/v7` to the platform list.
> > 
> > 
> > is still missing. Would you like me to commit it somewhere or you guys can do it?
> 
> I created this PR, is it what you where thinking to add ? #1616

Yeah, that's exactly it. Sorry I've missed that, thank you again!

**Comment by GuillaumeDSM** [comment]
Thank you for quickly noticing the issue !

**Pull request merged**
