### PR TITLE
Gitpodify OctoBot

### PR DESCRIPTION
**Pull request by KapadiaNaitik**
Thank you for sending your pull request. 
But first, have you included unit tests, and is your code PEP8 conformant? [More details](https://github.com/Drakkar-Software/OctoBot/blob/dev/CONTRIBUTING.md)

## Summary
Gives the Ability to Try out OctoBot on cloud with one click with automated setup.

## Changelog

  - Updated .gitpod.yml file

## What's new?
*Gives Ability to Try out OctoBot on cloud with one click,user doesn't have to go through hassle of setting it up.It will automatically run all commands for the user.
*Helps to preview changes made in PR

### CODE REVIEW

**Review by Herklos — COMMENTED** [review]
Thanks @KapadiaNaitik! Could you please create a new section # Contribute before Disclamer where you can put gitpod instriuctions.

**Comment by KapadiaNaitik** [comment]
> Thanks @KapadiaNaitik! Could you please create a new section # Contribute before Disclamer where you can put gitpod instriuctions.

@Herklos sure thing! added the Contribute section

**Comment by Herklos** [comment]
> > Thanks @KapadiaNaitik! Could you please create a new section # Contribute before Disclamer where you can put gitpod instriuctions.
> 
> @Herklos sure thing! added the Contribute section

Thanks. It was not clear. Can you add it after the "Exchanges" part and before "Disclamer" please ?

**Comment by KapadiaNaitik** [comment]
> > > Thanks @KapadiaNaitik! Could you please create a new section # Contribute before Disclamer where you can put gitpod instriuctions.
> > 
> > 
> > @Herklos sure thing! added the Contribute section
> 
> Thanks. It was not clear. Can you add it after the "Exchanges" part and before "Disclamer" please ?

Sorry for the confusion.Fixed the positioning of  Contribute in Readme.

**Review by Herklos — APPROVED** [review]
Thanks @KapadiaNaitik!

**Comment by GuillaumeDSM** [comment]
Hi @KapadiaNaitik, thanks for contributing ! 
We are updating the dev branch first and we then merge it into master. I just changed the target branch to merge your PR into dev, could you please rebase your branch onto Drakkar-Softwate:dev plz ? Then we will merge it.

**Pull request merged**
